version: '3.7'
services:
    service-1:
        build:
            context: ./service-1
            dockerfile: Dockerfile
        image: steve/service-1
        ports:
        - target: 5001
          published: 5001
    service-2:
        build:
            context: ./service-2
            dockerfile: Dockerfile
        image: steve/service-2
        ports:
        - target: 5002
          published: 5002
    service-3:
        build:
            context: ./service-3
            dockerfile: Dockerfile
        image: steve/service-3
        ports:
        - target: 5003
          published: 5003
    service-4:
        build:
            context: ./service-4
            dockerfile: Dockerfile
        image: steve/service-4
        ports:
        - target: 5000
          published: 5000